### PR TITLE
Here is some improvements

### PR DESCRIPTION
**Pull request by v-v-vishnevskiy**

### CODE REVIEW

**Comment by p2** [comment]
Thanks for this! Several comments:

- please keep ignoring `./settings.py` and don't change/move `Python/settings.py`. As written in the readme, to generate data models you must first copy settings.py from either the _Python_ or _Swift_ directories; this is intentional. [Here's](https://github.com/smart-on-fhir/client-py/blob/master/generate_models.sh) an example of how we start generating.
- What's the purpose of the `cast` argument?
- I'm not sure about the type checks in `as_json()`. If you provide a non-list to a property that's supposed to be a list, you're making a programmer error that should crash. Otherwise you may be wondering why your data model is forgetting to serialize properties that you've set. What's your take?

**Comment by v-v-vishnevskiy** [comment]
> please keep ignoring ./settings.py...

Fix this. Sorry.
https://github.com/smart-on-fhir/fhir-parser/pull/11/commits/c968abd2258c38090121a212626e48e2fd13b297

> What's the purpose of the cast argument?

For example,
`Patient(json.jsons('....'))` – All data for each field will be in strings. But I need to output data casted by FHIR schema.

> I'm not sure about the type checks in as_json()...

For example, a Patient resource has `address` field which must be a list. If I pass it as non-list then it data is not valid by FHIR schema and must not be serialized. It data can come from user browser or anywhere else and model do not pass not valid data. Am I right?)

**Comment by p2** [comment]
> Fixed this. Sorry.
> https://github.com/smart-on-fhir/fhir-parser/pull/11/commits/c968abd2258c38090121a212626e48e2fd13b297

Well, this moves some configuration from the settings file to the script, which is not ideal, not least because it breaks both our clients integrations. The intent is to write your own settings file where you import the default settings and overwrite what you want to overwrite. This is by intent so you can embed fhir-parser in projects and easily overwrite all settings.

> For example,
> `Patient(json.jsons('....'))` – All data for each field will be in strings. But I need to output data casted by FHIR schema.

Can you make a concrete example where you have a problem? Initializing `Patient({"id": "..."})` with JSON data will already convert it to the correct FHIR types, without the cast argument.

> For example, a Patient resource has `address` field which must be a list. If I pass it as non-list then it data is not valid by FHIR schema and must not be serialized. It data can come from user browser or anywhere else and model do not pass not valid data. Am I right?

Well, assigning a non-list to a list property is a programmer error and should crash. You are responsible to validating user input. An extensive checking system is desirable, but that must also check constraints on the profile and should not fail silently. So for now I don't think this is a good idea.

**Comment by v-v-vishnevskiy** [comment]
> Can you make a concrete example where you have a problem? Initializing Patient({"id": "..."}) with JSON data will already convert it to the correct FHIR types, without the cast argument.

For example,
`Patient({'active': 'on'}).as_json()` will return `{'active': 'on'}`, but FHIR standard requires that it field must be a boolean. So I add parameter `cast` and `Patient({'active': 'on'}).as_json(True)` will return `{'active': True}`

**Comment by v-v-vishnevskiy** [comment]
> Well, this moves some configuration from the settings file to the script, which is not ideal, not least because it breaks both our clients integrations. The intent is to write your own settings file where you import the default settings and overwrite what you want to overwrite. This is by intent so you can embed fhir-parser in projects and easily overwrite all settings.

I think that parameters from command-line much better than copying some files and edit it.
When you run `./generate -h` it show you all parameters.

**Comment by p2** [comment]
> For example,
> Patient({'active': 'on'}).as_json() will return {'active': 'on'}, but FHIR standard requires that it field must be a boolean. So I add parameter cast and Patient({'active': 'on'}).as_json(True) will return {'active': True}

But `"active": "on"` is not valid in FHIR, `active` must be a bool. This should actually raise an Exception, but it doesn't do so because we haven't built a good type checking system for `update_with_json ()` just yet.

> I think that parameters from command-line much better than copying some files and edit it.
When you run ./generate -h it show you all parameters.

Generally, sure, but _fhir-parser_ is usually used as a sub-module to a client library, like [client-py](https://github.com/smart-on-fhir/client-py) or [Swift-FHIR](https://github.com/smart-on-fhir/Swift-FHIR). As such it needs to be configured, hence it makes sense to put configuration into a file. The URL pointing to the FHIR release you want to use, whether you want unit tests, how these should be named, and so on. I don't think it's desirable to expose all these through command line arguments, so it's not necessary to expose some settings via command line; better to keep them all in one place.

I'd be happy to pull in the no-crash change in FHIRDate, but I don't agree with the other changes.

**Comment by p2** [comment]
Also, see #8 for more discussion around validation.

**Comment by v-v-vishnevskiy** [comment]
> But "active": "on" is not valid in FHIR, active must be a bool. This should actually raise an Exception, but it doesn't do so because we haven't built a good type checking system for update_with_json () just yet.

May be I move this cast to `update_with_json ()` method?

**Comment by p2** [comment]
The problem with this approach is that the Python data models are also used server-side, not only client-side where being lenient with the data you get is desirable. I agree that casting from string values like "false" to a boolean _false_ is useful in clients, but this should not live in the base data models.

The generator is widely used, so what I suggest you do is create your own Python client, which uses _fhir-parser_ and which supplies its own `fhirabstractbase` class – such as you have here. There you can add even more client-specific logic without affecting other uses of the generator's very basic models.

Does this make sense?

**Comment by p2** [comment]
language specific files have now been moved to the client repositories, now you should be able to use `fhir-parser` with your own base classes without needing to change the parser itself. 👍🏼

**Pull request closed without merging**
